[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "watchman-pairing-assistant"
version = "2.2.1"
description = "GUI for pairing SteamVR Tracking devices using lighthouse_console"
readme = "README.md"
dependencies = [
  "customtkinter>=5.2.2,<6.1.0",
  "libusb-package>=1.0.26.2,<1.0.31.0",
  "pyusb>=1.2.1,<1.4.0",
  "pillow>=10.0.0,<13.0.0",
  "hidapi>=0.14.0,<1.0.0",
]
license = "MIT"

[project.scripts]
watchman-pairing-assistant = "main:main"

[tool.setuptools]
package-dir = { "" = "source" }
py-modules = ["main", "usb_util", "dongle_watcher"]

[tool.setuptools.data-files]
"share/applications" = ["resources/watchman-pairing-assistant.desktop"]
"share/icons/hicolor/256x256/apps" = ["resources/watchman-pairing-assistant.png"]
