name: Assign Issue to Copilot

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: otto-de/assign_issue_toCopilot_action@a03c632341e7921e04a90e9b1bd68aae82251bfb # main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
