name: "Build Executable (Windows)"

on:
  push:
    branches:
      - main

jobs:
  build-exe:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Task
        uses: arduino/setup-task@v2
      - run: task dist
      - uses: actions/upload-artifact@v4
        with:
          path: dist/main.exe
          name: executable
